print("Welcome to Abdulqoyum's tip calculator")
bill = input("Enter your bill\n$")
bill_integer = float(bill)
percent_tip = input("What percentage tip would you like to give? 7, 10 or 12?\n")
tip_integer = int(percent_tip)
bill = bill_integer + (tip_integer / 100 * bill_integer)
noofpeople = input("How many people should split the bill?\n")
noofpeople = int(noofpeople)
print("Each person should pay ${}".format(round(bill / noofpeople, 2)))
